export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[];
export type Database={public:{Tables:{
terms:{Row:{id:string;name:string;year:number;is_active:boolean;created_at:string;updated_at:string};Insert:{id?:string;name:string;year:number;is_active?:boolean;created_at?:string;updated_at?:string};Update:Partial<Database["public"]["Tables"]["terms"]["Insert"]>;Relationships:[]};
groups:{Row:{id:string;term_id:string;name:string;created_at:string};Insert:{id?:string;term_id:string;name:string;created_at?:string};Update:Partial<Database["public"]["Tables"]["groups"]["Insert"]>;Relationships:[]};
participants:{Row:{id:string;group_id:string;name:string;grade:number;is_active:boolean;created_at:string;updated_at:string};Insert:{id?:string;group_id:string;name:string;grade:number;is_active?:boolean;created_at?:string;updated_at?:string};Update:Partial<Database["public"]["Tables"]["participants"]["Insert"]>;Relationships:[]};
criteria:{Row:{id:string;term_id:string;name:string;kind:string;sort_order:number;is_active:boolean;created_at:string;updated_at:string};Insert:{id?:string;term_id:string;name:string;kind?:string;sort_order?:number;is_active?:boolean;created_at?:string;updated_at?:string};Update:Partial<Database["public"]["Tables"]["criteria"]["Insert"]>;Relationships:[]};
scores:{Row:{id:string;participant_id:string;criterion_id:string;value:number;note:string|null;created_at:string;updated_at:string};Insert:{id?:string;participant_id:string;criterion_id:string;value?:number;note?:string|null;created_at?:string;updated_at?:string};Update:Partial<Database["public"]["Tables"]["scores"]["Insert"]>;Relationships:[]};
staff_profiles:{Row:{user_id:string;role:string;group_id:string|null;created_at:string;updated_at:string};Insert:{user_id:string;role:string;group_id?:string|null;created_at?:string;updated_at?:string};Update:Partial<Database["public"]["Tables"]["staff_profiles"]["Insert"]>;Relationships:[]};
recognitions:{Row:{id:string;term_id:string;participant_id:string;type:string;week_date:string|null;event_date:string|null;note:string|null;created_at:string};Insert:{id?:string;term_id:string;participant_id:string;type:string;week_date?:string|null;event_date?:string|null;note?:string|null;created_at?:string};Update:Partial<Database["public"]["Tables"]["recognitions"]["Insert"]>;Relationships:[]};
}};Functions:{current_staff_role:{Args:never;Returns:string};current_staff_group_id:{Args:never;Returns:string}}}};
